namespace Pulse.Core
{
    public enum FFXIIITextTagIcon : byte
    {
        Clock = 0x40,
        Attention = 0x41,
        Exclamation = 0x42,
        EmptryCirlces = 0x43,
        Greather = 0x44,
        Less = 0x45,
        Doc = 0x46,
        Ok = 0x47,
        FilledCirlces = 0x48,

        // Bad names... -_-
        Gunblade,
        Shotgun,
        Weapon03,
        Boomerang,
        Rod,
        Glaive,
        AxisBlade,
        Katar,
        Weapon09,
        Shield01,
        Wrench,
        Note,
        Screw,
        Material01,
        Bracert,
        Ring,
        Earring,
        Brooch,
        Potion01,
        Potion02,
        Potion03,
        Feather,
        Cloth,
        Item,
        Eye01,
        Sword01,
        Staff01,
        Shield02,
        HealthUp,
        Imperial,
        Ugly,
        Rage,
        Provoke,
        Sword02,
        Shield03,
        Staff,
        Up,
        Kn,
        Yu,
        Rudder,
        Eye02,
        Ribbon,
        Sphere,
        Neck
    }
}